# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 16:17
from __future__ import unicode_literals

import TechnexUser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentEvent',
            fields=[
                ('parentEventId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnexUser.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TechProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth'), (5, b'Fifth')])),
                ('mobile_number', models.BigIntegerField()),
                ('profile_photo', models.ImageField(default=None, upload_to=TechnexUser.models.get_user_image_folder)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechnexUser.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ca', models.BooleanField(default=False)),
                ('is_techuser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', to='TechnexUser.TechProfile'),
        ),
        migrations.AddField(
            model_name='team',
            name='teamLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeader', to='TechnexUser.TechProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='parentEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnexUser.ParentEvent'),
        ),
    ]
