# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_message', models.TextField()),
                ('mark_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poster_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('poster_1', models.ImageField(upload_to=b'posters')),
                ('poster_2', models.ImageField(upload_to=b'posters')),
                ('poster_3', models.ImageField(upload_to=b'posters')),
                ('poster_4', models.ImageField(upload_to=b'posters')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('mark_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth'), (5, b'Fifth')])),
                ('mobile_number', models.PositiveIntegerField()),
                ('whatsapp_number', models.PositiveIntegerField()),
                ('college', models.CharField(max_length=250)),
                ('college_address', models.TextField()),
                ('postal_address', models.TextField()),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massnotification',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
