# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth'), (5, b'Fifth')])),
                ('mobile_number', models.PositiveIntegerField()),
                ('whatsapp_number', models.PositiveIntegerField()),
                ('college', models.CharField(max_length=100)),
                ('college_address', models.TextField(max_length=250)),
                ('postal_address', models.TextField()),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
    ]
