# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massnotification',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 17, 16, 21, 33, 353000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotification',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 17, 16, 21, 40, 530000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='poster_1',
            field=models.ImageField(upload_to=b'posters/%m/%d'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='poster_2',
            field=models.ImageField(upload_to=b'posters/%m/%d'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='poster_3',
            field=models.ImageField(upload_to=b'posters/%m/%d'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='poster_4',
            field=models.ImageField(upload_to=b'posters/%m/%d'),
        ),
    ]
