# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='CAProfile',
        ),
    ]
