# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massnotification',
            old_name='user',
            new_name='ca',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='user',
            new_name='ca',
        ),
        migrations.RenameField(
            model_name='usernotification',
            old_name='user',
            new_name='ca',
        ),
    ]
