# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 04:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_auto_20160901_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnexUser',
        ),
        migrations.RemoveField(
            model_name='caprofile',
            name='profile_completed',
        ),
        migrations.AddField(
            model_name='caprofile',
            name='profile_photo',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='mobile_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='whatsapp_number',
            field=models.PositiveIntegerField(),
        ),
    ]
