# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_auto_20160817_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massnotification',
            name='mark_read',
        ),
    ]
