# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('ca', '0004_auto_20160816_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('poster1', models.ImageField(upload_to=b'posters')),
                ('poster2', models.ImageField(upload_to=b'posters')),
                ('poster3', models.ImageField(upload_to=b'posters')),
            ],
        ),
    ]
