# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='poster4',
            field=models.ImageField(default=datetime.datetime(2016, 8, 16, 18, 33, 0, 429000, tzinfo=utc), upload_to=b'posters'),
            preserve_default=False,
        ),
    ]
