# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0006_poster_poster4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='poster1',
            new_name='poster_1',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='poster2',
            new_name='poster_2',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='poster3',
            new_name='poster_3',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='poster4',
            new_name='poster_4',
        ),
    ]
